# -*- coding: utf-8 -*-
"""numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0I3S7Hrw2ehV7cNBi6X3U_4tEv9RwOY
"""

integer1, integer2, integer3 = int(input("Enter three different integers: ")), int(input()), int(input()) #asks the user to enter three different integers
sum = integer1 + integer2 + integer3 #sum of the three integers
print(sum) #print of sum
sub = integer1 - integer2 #subtraction of integer2 from integer1
print(sub) #print subtraction
mult = integer3*integer1 #multiplication of integer3 with integer1
print(mult) #print multiplication
last_bullet = sum / integer3 #instructions from the last bullet point
print(last_bullet) #print instructions from the last bullet point