# -*- coding: utf-8 -*-
"""numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0I3S7Hrw2ehV7cNBi6X3U_4tEv9RwOY
"""

# asks the user to enter three different integers
integer_1, integer_2, integer_3 = int(input("Enter three different integers: ")), int(input()), int(input())

# addition of the three integers
sum = integer_1 + integer_2 + integer_3 
# print of their sum
print(sum)

# subtraction of integer2 from integer1
difference = integer_1 - integer_2 
# print of the difference
print(difference) 

# multiplication of integer3 with integer1
product = integer_3*integer_1 
# print the product of the multiplication
print(product) 

# instructions from the last bullet point
last_bullet = sum / integer_3 
# print the answer of the the last bullet point
print(last_bullet)
