# -*- coding: utf-8 -*-
"""numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0I3S7Hrw2ehV7cNBi6X3U_4tEv9RwOY
"""

# asks the user to enter three different integers
integer1, integer2, integer3 = int(input("Enter three different integers: ")), int(input()), int(input())

# sum of the three integers
sum = integer1 + integer2 + integer3 
# print of sum
print(sum)

# subtraction of integer2 from integer1
sub = integer1 - integer2 
# print subtraction
print(sub) 

# multiplication of integer3 with integer1
mult = integer3*integer1 
# print multiplication
print(mult) 

# instructions from the last bullet point
last_bullet = sum / integer3 
# print instructions from the last bullet point
print(last_bullet)