# -*- coding: utf-8 -*-
"""optional_task

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12eZDWRzNucbBVvmdg6QcHvmtjd1aa1pH
"""

side1, side2, side3 = float(input("Enter the length of each triagnle side in two decimals: ")), float(input()), float(input())
s = (side1 + side2 + side3)/2
area = (s(s-side1)*(s-side2)*(s-side3))**0.5 #Heron's formula for the area of the triangle #help error here
print(area)